import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { addDays, audit, availableSlots, loadState, now, saveState, today } from "../domain.js";

registerMainMenuItem({ label: "My booking", data: "booking:lookup", order: 20 });
const composer = new Composer<Ctx>();
const force = (placeholder: string) => ({ force_reply: true as const, input_field_placeholder: placeholder });
const menu = inlineKeyboard([[inlineButton("Back to menu", "menu:main")]]);

composer.callbackQuery("booking:lookup", async ctx => { await ctx.answerCallbackQuery(); ctx.session.step = "lookup"; await ctx.reply("Send your 6-character booking reference.", { reply_markup: force("Reference code") }); });
composer.on("message:text", async (ctx, next) => { if (ctx.session.step !== "lookup") return next(); const ref = ctx.message.text.trim().toUpperCase(); const state = await loadState(ctx); const booking = state.bookings.find(b => b.ref === ref && b.chatId === (ctx.chat?.id ?? 0)); if (!booking) { await ctx.reply("I couldn't find that booking. Check the reference and try again.", { reply_markup: menu }); return; } ctx.session.step = "idle"; await show(ctx, booking.ref); });
composer.callbackQuery(/^booking:details:([A-Z0-9]{6})$/, async ctx => { await ctx.answerCallbackQuery(); await show(ctx, ctx.match[1]); });
composer.callbackQuery(/^booking:cancel:([A-Z0-9]{6})$/, async ctx => { await ctx.answerCallbackQuery(); await ctx.reply("Cancel this booking?", { reply_markup: inlineKeyboard([[inlineButton("Confirm cancellation", `booking:cancel-confirm:${ctx.match[1]}`), inlineButton("Keep booking", `booking:details:${ctx.match[1]}`)]]) }); });
composer.callbackQuery(/^booking:cancel-confirm:([A-Z0-9]{6})$/, async ctx => { await ctx.answerCallbackQuery(); const state = await loadState(ctx); const b = state.bookings.find(x => x.ref === ctx.match[1] && x.chatId === (ctx.chat?.id ?? 0)); if (!b || b.status !== "confirmed") { await ctx.reply("That booking is no longer active.", { reply_markup: menu }); return; } b.status = "cancelled"; b.updatedAt = now().toISOString(); audit(state, "cancel", "guest", b.id); await saveState(ctx, state); await ctx.reply(`Your booking ${b.ref} is cancelled.`, { reply_markup: menu }); await notifyOwner(ctx, `Booking ${b.ref} was cancelled.`); });
composer.callbackQuery(/^booking:reschedule:([A-Z0-9]{6})$/, async ctx => { await ctx.answerCallbackQuery(); const state = await loadState(ctx); const b = state.bookings.find(x => x.ref === ctx.match[1] && x.chatId === (ctx.chat?.id ?? 0)); if (!b || b.status !== "confirmed") { await ctx.reply("That booking is no longer active.", { reply_markup: menu }); return; } await ctx.reply("Move this booking to a new time?", { reply_markup: inlineKeyboard([[inlineButton("Choose a new time", `booking:reschedule-go:${ctx.match[1]}`), inlineButton("Keep booking", `booking:details:${ctx.match[1]}`)]]) }); });
composer.callbackQuery(/^booking:reschedule-confirm:([A-Z0-9]{6})$/, async ctx => { await ctx.answerCallbackQuery(); await ctx.reply("Move this booking to a new time?", { reply_markup: inlineKeyboard([[inlineButton("Choose a new time", `booking:reschedule-go:${ctx.match[1]}`), inlineButton("Keep booking", `booking:details:${ctx.match[1]}`)]]) }); });
composer.callbackQuery(/^booking:reschedule-go:([A-Z0-9]{6})$/, async ctx => { await ctx.answerCallbackQuery(); const state = await loadState(ctx); const b = state.bookings.find(x => x.ref === ctx.match[1] && x.chatId === (ctx.chat?.id ?? 0)); if (!b) { await ctx.reply("I couldn't find that booking.", { reply_markup: menu }); return; } ctx.session.bookingId = b.id; ctx.session.partySize = b.partySize; ctx.session.step = "reschedule_date"; await ctx.reply("Choose a new date for your booking.", { reply_markup: dates(state, b.partySize, b.id) }); });
composer.callbackQuery(/^booking:resdate:(\d{4}-\d{2}-\d{2})$/, async ctx => { await ctx.answerCallbackQuery(); ctx.session.date = ctx.match[1]; ctx.session.step = "reschedule_time"; const state = await loadState(ctx); const b = state.bookings.find(x => x.id === ctx.session.bookingId); const times = b ? availableSlots(state, ctx.session.date, b.partySize, b.id) : []; const rows = []; for (let i = 0; i < times.length; i += 3) rows.push(times.slice(i, i + 3).map(t => inlineButton(t, `booking:restime:${t}`))); await ctx.reply(times.length ? "Pick a new time." : "That date is full. Choose another date.", { reply_markup: times.length ? inlineKeyboard(rows) : menu }); });
composer.callbackQuery(/^booking:restime:(\d{2}:\d{2})$/, async ctx => { await ctx.answerCallbackQuery(); const state = await loadState(ctx); const b = state.bookings.find(x => x.id === ctx.session.bookingId); if (!b || !availableSlots(state, ctx.session.date ?? today(), b.partySize, b.id).includes(ctx.match[1])) { await ctx.reply("That time was just taken. Choose another time."); return; } const old = `${b.date} at ${b.time}`; b.status = "rescheduled"; b.date = ctx.session.date ?? b.date; b.time = ctx.match[1]; b.status = "confirmed"; b.rescheduleCount++; b.updatedAt = now().toISOString(); audit(state, "reschedule", "guest", b.id, `${old} to ${b.date} at ${b.time}`); await saveState(ctx, state); ctx.session.step = "idle"; await ctx.reply(`Your booking is moved to ${b.date} at ${b.time}.\nReference: ${b.ref}`, { reply_markup: inlineKeyboard([[inlineButton("View details", `booking:details:${b.ref}`), inlineButton("Back to menu", "menu:main")]]) }); await notifyOwner(ctx, `Booking ${b.ref} was rescheduled to ${b.date} at ${b.time}.`); });

function dates(state: Awaited<ReturnType<typeof loadState>>, size: number, exclude?: string) { const rows = []; for (let i = 0; i < 7; i++) { const date = addDays(today(), i); if (availableSlots(state, date, size, exclude).length) rows.push([inlineButton(i === 0 ? "Today" : date, `booking:resdate:${date}`)]); } return inlineKeyboard(rows.concat([[inlineButton("Back to menu", "menu:main")]])); }
async function show(ctx: Ctx, ref: string) { const state = await loadState(ctx); const b = state.bookings.find(x => x.ref === ref && x.chatId === (ctx.chat?.id ?? 0)); if (!b) { await ctx.reply("I couldn't find that booking. Check the reference and try again.", { reply_markup: menu }); return; } await ctx.reply(`Booking ${b.ref}\n${b.date} at ${b.time} for ${b.partySize} people\nStatus: ${b.status}`, { reply_markup: b.status === "confirmed" ? inlineKeyboard([[inlineButton("Reschedule", `booking:reschedule:${b.ref}`), inlineButton("Cancel", `booking:cancel:${b.ref}`)], [inlineButton("Back to menu", "menu:main")]]) : menu }); }
async function notifyOwner(ctx: Ctx, text: string) { const env = (ctx as Ctx & { env?: Record<string, unknown> }).env; const id = env?.ADMIN_CHAT_ID ?? (typeof process === "undefined" ? undefined : process.env.ADMIN_CHAT_ID); if (id) { try { await ctx.api.sendMessage(String(id), text); } catch { /* owner notification is best effort */ } } }
export default composer;
